# Generated by Django 5.2.2 on 2025-06-07 23:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('error', models.TextField(blank=True, null=True)),
                ('result', models.JSONField(default=dict)),
                ('message', models.TextField()),
            ],
        ),
    ]
