# Generated by Django 5.2.2 on 2025-06-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='status',
            new_name='state',
        ),
    ]
