# Generated by Django 5.2.2 on 2025-06-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_worker_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='input_params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='name',
            field=models.TextField(default='Worker'),
        ),
    ]
