# Generated by Django 5.2.3 on 2025-06-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dataset_image_datasetimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='type',
            field=models.CharField(default='mock', max_length=50),
        ),
    ]
